service: choreapp-client

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: choreapp-client-dev
    distributionFolder: /build
    indexDocument: index.html
    errorDocument: index.html
