service: hubworld-posts-server
app: hubworld
org: lmuller18

provider:
  name: aws
  runtime: nodejs10.x
  package:
    individually: true
    exclude:
      - node_modules

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    port: 4002
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'

functions:
  posts:
    handler: src/handler.handler
    events:
      - http:
          path: api
          method: post
          cors: true
