service: choreapp-gateway
app: choreapp
org: zclabs

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  package:
    individually: true
    exclude:
      - node_modules

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
    packager: "yarn"

functions:
  gateway:
    handler: src/app.handler
    environment:
      ACCOUNTS_FEDERATION_URL: ${file(./serverless.env.yml):${self:provider.stage}.ACCOUNTS_FEDERATION_URL}
      CHORES_FEDERATION_URL: ${file(./serverless.env.yml):${self:provider.stage}.CHORES_FEDERATION_URL}
      NOTIFICATIONS_FEDERATION_URL: ${file(./serverless.env.yml):${self:provider.stage}.NOTIFICATIONS_FEDERATION_URL}
      DYNAMO_DB_ENV: ${file(./serverless.env.yml):${self:provider.stage}.DYNAMO_DB_ENV}
    events:
      - http:
          path: api
          method: post
          cors: true
